### ISSUE TITLE
[Bug]: Textfield in the background of the Home_page

### ISSUE THREAD

**Issue by ClementGld** [lenra-io/client#6] opened 2022-06-14 09:11 UTC
## What should be done 
After a login we have the page, home_page.dart, in this page between the two texts: "Lenra is under development" and "To access an application you must have its link provided by its creator." We can select a text that is the email address, we cannot see it. This text does not appear if we do not go into the login before we do not have this problem.

## Technical recommandation
I think it's the text field on the login page that appears behind the home page.
To see this text, you can select it and drag and drop it into a text field in your browser.

**Comment by jonas-martinez** [comment] 2023-02-01 15:37
I cannot reproduce this issue, it may have been fixed by the new navigation system.

**Closed by jonas-martinez** 2023-02-01 15:37 UTC
Labels: bug, help wanted
